---
title: "Project 1"
author: "Michael Costello"
format: html
editor: source
---

#541a25ef175ec8d1abf1a4b9bb864ac88cf70e54
```{r}
trial_run <- httr::GET("https://api.census.gov/data/2021/acs/acs1/pums?get=AGEP,GASP,GRPIP,JWAP,JWDP,JWMNP,PWGTP,FER,HHL,SCH,SCHL,SEX,ST,REGION&for=DIVISION:5&key=541a25ef175ec8d1abf1a4b9bb864ac88cf70e54")
  parsed_data <- fromJSON(rawToChar(trial_run$content))
  api_result <- parsed_data |>
      janitor::row_to_names(row_number = 1) |>
      as_tibble() |>
      type_convert()
```

# Part  1 - Data Processing

I'm going to use R's api functions to pull PUMS data down from the US Census website.

```{r}
#| message: false
#| warning: false

library(tidyverse)
library(httr)
library(jsonlite)
library(janitor)
install.packages("cli")
library(cli)
```
## Parsing Variable Values (i.e. labels)
Getting one year first.
```{r}
variable_json <- httr::GET("https://api.census.gov/data/2021/acs/acs1/pums/variables.json")

#str(variable_json, max.level = 1)
parsed_labels <- fromJSON(rawToChar(variable_json$content))
subset_labels <- parsed_labels$variables[c("AGEP","GASP","GRPIP","JWAP","JWDP", "JWMNP","PWGTP","FER","HHL","SCH","SCHL","SEX","ST","REGION","DIVISION")]
saveRDS(subset_labels, file = "data/variable_descriptions.rds")
```
Creating a loop
```{r}
years <- 2021:2024
for (yr in years) {
  #Create some strings that I'll need to make the loops run correctly
  api_str <- paste0("https://api.census.gov/data/",yr,"/acs/acs1/pums/variables.json")
  save_str <- paste0("data/variable_descriptions_",yr,".rds")
  
  #Actually collect the data from Census
  variable_json <- httr::GET(api_str)

  #Parse and subset the lists
  parsed_labels <- fromJSON(rawToChar(variable_json$content))
  if(yr <= 2022) {
    subset_labels <- parsed_labels$variables[c("AGEP","GASP","GRPIP","JWAP","JWDP", "JWMNP","PWGTP","FER","HHL","SCH","SCHL","SEX","ST","REGION","DIVISION")]
    #rename ST to STATE to make all more comparable later.
    names(subset_labels)[13] <- "STATE" 
  }
  else subset_labels <- parsed_labels$variables[c("AGEP","GASP","GRPIP","JWAP","JWDP", "JWMNP","PWGTP","FER","HHL","SCH","SCHL","SEX","STATE","REGION","DIVISION")]
  
  #Save the output
  saveRDS(subset_labels, file = save_str)
}
```



## Parsing API Data

```{r}
helper <- function(year = 2024, vars = c(), restrictions = c()) {

  #Generate all the input parameters:
    address <- "https://api.census.gov/data/"
    vars_allowed <- c("AGEP", "GASP", "GRPIP", "JWAP", "JWDP", "JWMNP", "JWMNP", "PWGTP","FER","HHL","SCH","SCHL","SEX","ST","STATE","REGION","DIVISION")
    #Create separate lists of geo, str, and num vars for further checking
      numeric_vars <- c("AGEP","GASP","GRPIP","JWAP","JWDP","JWMNP")
      string_vars  <- c("FER","HHL","SCH","SCHL","SEX")
      geography_vars<- c("ST","STATE","REGION","DIVISION")
  
  #Check singularity and validity of the year
  if (length(year) != 1) {
    stop("Slow down One Direction, the argument 'year' must be a single value, not a vector or list.")
  }
  if (!year %in% c(2021, 2022, 2023, 2024)) {
    stop("Hey *NSync, the argument 'year' must be ONE of the following: 2021, 2022, 2023, 2024.")
  }

  #Check the requested variables
  if (length(vars) == 0) {
    final_request_vars <- "AGEP,PWGTP,SEX"
  } else {
      #Check to make sure all requested vars are allowed.
      if (!all(vars %in% vars_allowed)) {
      #rlang::arg_match(vars, vars_allowed, multiple = TRUE)
        stop("Yo, New Kids on the Block, you chose variables that are not in our list. Please restrict to numeric variables: AGEP, GASP, GRPIP, JWAP, JWDP, JWMNP, and to categorical varailes: FER, HHL, SCH, SCHL, SEX.")
      }

      #Create separate lists of the requested variables for each type
       req_num_vars <- paste(vars[vars %in% numeric_vars], collapse = ",")
       req_str_vars <- paste(vars[vars %in% string_vars], collapse = ",")
       req_geo_vars <- paste(vars[vars %in% geography_vars], collapse = ",")
       
       #Push out defaults, in case nothing is listed (in a sub category)
       if (nchar(req_num_vars) == 0) req_num_vars <- "AGEP"
       if (nchar(req_str_vars) == 0) req_str_vars <- "SEX"
       if (nchar(req_geo_vars) == 0) {
         if (year <= 2022) req_geo_vars <- "ST"
         else req_geo_vars <- "STATE"
       } else {
         ###### Strip State out of req_geo_vars
       }
       #Glue the requested variable strings all together
       final_request_vars <- paste(req_num_vars,req_str_vars,req_geo_vars,"PWGTP", sep = ",")
  }

  #Subset the API Request, so as not to get too much data.
  if (length(restrictions) == 0) {
    message("Whoa, High School Musical, that's too much data. Census will cut you off. We are going to trim that down to just STATE:44 (because Rhode Island is awesome) and go from there. You can cange this by adding a geographic variable (STATE/ST, REGION, etc.) or some other restriction to the `restrictions` parameter. IF you really want it all, try `STATE:all`.")
    if(year <= 2022) final_restrict <- "&for=ST:44"
    else final_restrict <- "&for=STATE:44"
  } else if (restrictions == "STATE:all" || restrictions == "ST:all") {
    message("Wow Vomit Comet, that's going to be a ton of data (from all 51 states), but I'm with you, I'm your ride-or-die!")
    final_restrict <- ""
    if (year <= 2022) {
      final_request_vars <- paste(final_request_vars,"ST", sep = ",")
    } else {
      final_request_vars <- paste(final_request_vars,"STATE", sep = ",")
    }
  } else {
    #Make sure there are no spaces in the restrictions request
    restrictions <- gsub("\\s+", "", restrictions)
    #If the restrictions variable isn't empty, strip off the first bit to use later
    restrict_var <- sub("[=:].*", "", restrictions)
    
    ############################################################
    #Make sure that if STATE is used in 2021-2, it's changed to ST, and if ST is used in 2023-4, it's changed to STATE.
    ############################################################
    
    #Quick detour:Remove the restriction var if it's in the called vars list.
    final_request_vars <- gsub(restrict_var, "", final_request_vars)
    #remove double commas from call, if they exist
    final_request_vars <- gsub(",,", ",", final_request_vars)  
    
    #Now check if that first bit is geographical or not.
    if(restrict_var %in% geography_vars) {
      
      #Check to ensure values requested are in our list of allowed values
      requested_region <- str_split_i(restrictions, ":", 2) #extract the number
      requested_region <- as.integer(requested_region) #Convert # for analysis
      if (restrict_var == "STATE"){
        if (requested_region < 1 || requested_region == 3 || requested_region == 7 || requested_region == 14 || requested_region == 43 || requested_region == 52 || requested_region > 56) {
          cli::cli_abort("No no NO, Jonas Brother, you are asking for some STATE FIPS code we don't have. Stick to the 50 + DC. {.url https://www2.census.gov/geo/docs/reference/codes2020/national_state2020.txt}")
        }
      } else if (restrict_var == "REGION"){
        if (requested_region > 4|| requested_region > 4) {
          stop("Ahoy, Troubled Youth, ACS uses the standard 4 census regions, numbered 1 to 4.")
        }
      } else if (restrict_var == "DIVISION") {
        if (requested_region < 1 || requested_region > 9) {
          stop("Just stop Malibu Ken, ACS uses the standard 9 census divisions, numbered 1 to 9.")
        }
      }
      
      #If it is geographical, make sure it has a colon and not an equal sign
      restrictions <- sub("[=].*", ":.*", restrictions)
      
      #Then paste in the prefix for searching
      final_restrict <- paste0("&for=",restrictions)
    } else final_restrict <- paste0("&",restrictions)
  }

  #Create the final API , while making sure there are no spaces in it.
  final_api <- gsub("\\s+", "", paste0(address,year,"/acs/acs1/pums?get=",final_request_vars,final_restrict,"&key=541a25ef175ec8d1abf1a4b9bb864ac88cf70e54"))

  #Call the API, parse the data
  variable_json <- httr::GET(final_api)
  parsed <- fromJSON(rawToChar(variable_json$content))

  #Make API result into tibble, save it, and display it in the log
  api_result <- parsed |>
    janitor::row_to_names(row_number = 1) |>
    as_tibble() |>
    type_convert()
  
  #Manipulate the data in the tibble, adding labels to categorical, dates to date variables, converting numeric-seen-as-strings to true numeric
  final_data <- api_result
  
  #Time (ha ha, get it, time!) to label some variables, including the time vars.
    #Create the path for the labels file:
    label_path <- paste0("data/variable_descriptions_",year,".rds")
    my_labels <- readRDS(label_path)
    for (vrbls in c(string_vars, numeric_vars, geography_vars)) {
      label_address <- paste0("!!!my_labels$",vrbls,"$values$item")
      
      current_labels <- my_labels[[vrbls]][["values"]][["item"]]
      
      if (!is.null(current_labels) && has_name(final_data, vrbls)) {
        final_data <- final_data %>%
          mutate(!!vrbls := recode(.data[[vrbls]], !!!current_labels))
      }
    }
  
  View(final_data)
  class(final_data) <- c("census", class(final_data))
  return(final_data)
}


yr2021a <- helper(year = 2021)  #Should no longer fail, because of ST vs STATE.
yr2021b <- helper(year = 2021, vars = c("GASP","GRPIP")) 
yr2024c <- helper(vars = c("FER", "SEX"))             #Default vars, year.
yr2024d <- helper(year = 2024, vars=c("AGEP", "JWMNP"))  #non-default vars
yr2024e <- helper(vars = c("AGEP", "SEX"), restrict = "SEX=1") #Adding restrictn
yr2022f <- helper(year = 2022, vars = c("AGEP", "SEX", "GASP", "GRPIP", "JWAP", "JWDP", "JWMNP", "FER","HHL","SCH","SCHL"), restrict = "REGION:1")
yr2021g <- helper(year = 2021, restrict="ST:all")
yr2021h <- helper(year = 2023, restrict="STATE:all")
yr2024s <- helper(vars=c("AGEP", "SEX"), restrict = "SEX = 1") #Spaces
yr2024t <- helper(year = 2024, vars=c("AGEP", "JWAP"), restrict = "REGION:1")

#TODO:
  #a: fails
  #b: fails on some kind of unreported geography. Similar to D, maybe.
  #c: working
  #d: working, but not stripping out state (as default) when there are no restrictions (state is inserted as restriction)
  #e: state is a string var.
  #f: working, state is a string var.
  #Date time variables - math part.
  #Fix problem with = sign in geography vars.
  #Baywatch the error messages




yr2020x <- helper(year = 2020)  #Should fail, year out of range.
yr20212 <- helper(year = c(2020,2021))  #Should fail, too many years.
yr2024x <- helper(vars=c("AGEP", "BAS"))  #Bad input variable.
yr2021x <- helper(year = 2021, restrict = "STATE:3")
yr2022x <- helper(year = 2022, restrict = "REGION:5")
yr2023x <- helper(year = 2023, restrict = "DIVISION:0")
```
## Combining Multiple Years

```{r}
multi_year <- function(years, vars, restrictions = "") {
  for (yrs in years) {
    paste0("multiple_yrs_",yrs) <- helper(year = yrs, vars, restrictions)
  }
  #Create a new column with the year.
  return(paste0("multiple_yrs_",yrs))
}

yr2024_Test1 <- helper(vars = c("FER", "SEX")) 

yr20212m<- multi_year(years = c(2021,2022), vars = c("FER", "SEX"))
```
# Part  2 - Writing a Generic Function for Summarizing

## Combining Multiple Years

```{r}
bite_me <- function(tibble_name, numeric_vars = c("AGEP","GASP","GRPIP"), categorical_vars = c("FER","HHL","SCH","SCHL","SEX")) {
  #Parse the inputs:
  
  #Run calculations on numeric
  results <- sapply(numeric_vars, )
  
} 




#Create separate lists of the requested variables for each type
       req_num_vars <- paste(vars[vars %in% numeric_vars], collapse = ",")
       req_str_vars <- paste(vars[vars %in% string_vars], collapse = ",")
       req_geo_vars <- paste(vars[vars %in% geography_vars], collapse = ",")
       
       #Push out defaults, in case nothing is listed (in a sub category)
       if (nchar(req_num_vars) == 0) req_num_vars <- "AGEP"
       if (nchar(req_str_vars) == 0) req_str_vars <- "SEX"
       if (nchar(req_geo_vars) == 0) {
         if (year <= 2022) req_geo_vars <- "ST"
         else req_geo_vars <- "STATE"
       }
```